name: wsu_go
description: Senior Design Project 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  # This adds the google fonts library to our application
  google_fonts: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/
